const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Plugins.Arr,
		C3.Plugins.Mouse,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Tilemap.Acts.SetTile,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Arr.Cnds.CompareXY
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Season: 0},
	{"1000s": 0},
	{"100s": 0},
	{"10s": 0},
	{"1s": 0},
	{"1000s2": 0},
	{"1000s3": 0},
	{"1000s4": 0},
	{D100s: 0},
	{D10s: 0},
	{D1s: 0},
	{Array: 0},
	{Sprite: 0},
	{Mouse: 0},
	{Sprite2: 0},
	{Tween: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{Text5: 0},
	{Text6: 0},
	{Text7: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Text8: 0},
	{Tilemap2: 0},
	{Text9: 0},
	{Text10: 0},
	{Text11: 0},
	{Text12: 0},
	{Text13: 0},
	{Text14: 0},
	{Pro03: 0},
	{Pro02: 0},
	{Pro04: 0},
	{Pro05: 0},
	{Pro06: 0},
	{Pro01: 0},
	{Pro00: 0},
	{Sprite22: 0},
	{Text15: 0},
	{Text16: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Text17: 0},
	{Text18: 0},
	{Text19: 0},
	{Text20: 0},
	{Text21: 0},
	{Text22: 0},
	{Text23: 0},
	{Pro07: 0},
	{Pro08: 0},
	{Pro10: 0},
	{Pro12: 0},
	{Pro14: 0},
	{Pro13: 0},
	{Pro11: 0},
	{Pro09: 0},
	{Text24: 0},
	{Text25: 0},
	{Text26: 0},
	{Text27: 0},
	{Text28: 0},
	{Text29: 0},
	{Text30: 0},
	{Pro15: 0},
	{Pro16: 0},
	{Pro18: 0},
	{Pro20: 0},
	{Pro22: 0},
	{Pro17: 0},
	{Pro19: 0},
	{Pro21: 0},
	{Text31: 0},
	{Sprite42: 0},
	{ProgressArray: 0},
	{AJAX: 0},
	{Text32: 0},
	{Text33: 0},
	{Text34: 0},
	{Text35: 0},
	{Text36: 0},
	{Text37: 0},
	{Text38: 0},
	{Text39: 0},
	{Text40: 0},
	{Text41: 0},
	{Text42: 0},
	{Text43: 0},
	{Text44: 0},
	{Text45: 0},
	{Pro23: 0},
	{Pro24: 0},
	{Pro25: 0},
	{Pro26: 0},
	{Pro27: 0},
	{Pro28: 0},
	{Pro29: 0},
	{Pro30: 0},
	{Pro31: 0},
	{Pro32: 0},
	{Pro33: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Text46: 0},
	{TextInput: 0},
	{TextInput2: 0},
	{Text47: 0},
	{Text48: 0},
	{Text49: 0},
	{Text50: 0},
	{Text51: 0},
	{Text52: 0},
	{Pro34: 0},
	{Pro35: 0},
	{Pro36: 0},
	{Pro37: 0},
	{Pro38: 0},
	{Pro39: 0},
	{Text53: 0},
	{Pro40: 0},
	{Pro41: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Pro42: 0},
	{Text54: 0},
	{Text55: 0},
	{Text56: 0},
	{Text57: 0},
	{Text58: 0},
	{Text59: 0},
	{Text60: 0},
	{Text61: 0},
	{Text62: 0},
	{Text63: 0},
	{Pro43: 0},
	{Pro44: 0},
	{Pro45: 0},
	{Pro46: 0},
	{Pro47: 0},
	{Pro48: 0},
	{Pro49: 0},
	{Text64: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Text65: 0},
	{Pro50: 0},
	{Text66: 0},
	{Text67: 0},
	{Text68: 0},
	{Text69: 0},
	{Text70: 0},
	{Text71: 0},
	{Text72: 0},
	{Pro51: 0},
	{Pro52: 0},
	{Pro53: 0},
	{Pro54: 0},
	{Pro55: 0},
	{Pro56: 0},
	{Pro57: 0},
	{Sprite32: 0},
	{Text73: 0},
	{Text74: 0},
	{Text75: 0},
	{Text76: 0},
	{Text77: 0},
	{Text78: 0},
	{Text79: 0},
	{Text80: 0},
	{Text81: 0},
	{Text82: 0},
	{Text83: 0},
	{Pro58: 0},
	{Pro59: 0},
	{Pro60: 0},
	{Pro61: 0},
	{Pro62: 0},
	{Pro63: 0},
	{Pro64: 0},
	{Pro65: 0},
	{Pro66: 0},
	{Pro67: 0},
	{Text84: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Text85: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Text86: 0},
	{Text87: 0},
	{Text88: 0},
	{Text89: 0},
	{Text90: 0},
	{Text91: 0},
	{Text92: 0},
	{Text93: 0},
	{Pro68: 0},
	{Pro69: 0},
	{Pro70: 0},
	{Pro71: 0},
	{Pro72: 0},
	{Pro73: 0},
	{Pro74: 0},
	{Pro75: 0},
	{Text94: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Text95: 0},
	{Pro76: 0},
	{Text96: 0},
	{Text97: 0},
	{Text98: 0},
	{Text99: 0},
	{Text100: 0},
	{Text101: 0},
	{Text102: 0},
	{Text103: 0},
	{Text104: 0},
	{Text105: 0},
	{Text106: 0},
	{Pro77: 0},
	{Pro78: 0},
	{Pro79: 0},
	{Pro80: 0},
	{Pro81: 0},
	{Pro82: 0},
	{Pro83: 0},
	{Pro84: 0},
	{Pro85: 0},
	{Pro86: 0},
	{Pro87: 0},
	{Text107: 0},
	{Text108: 0},
	{Text109: 0},
	{Text110: 0},
	{Text111: 0},
	{Text112: 0},
	{Text113: 0},
	{Text114: 0},
	{Pro88: 0},
	{Pro89: 0},
	{Pro90: 0},
	{Pro91: 0},
	{Pro92: 0},
	{Pro93: 0},
	{Pro94: 0},
	{Pro95: 0},
	{Text115: 0},
	{Sprite39: 0},
	{Text116: 0},
	{Text117: 0},
	{Text118: 0},
	{Text119: 0},
	{Text120: 0},
	{Text121: 0},
	{Text122: 0},
	{Text123: 0},
	{Text124: 0},
	{Text125: 0},
	{Pro96: 0},
	{Pro97: 0},
	{Pro98: 0},
	{Pro99: 0},
	{Pro100: 0},
	{Pro101: 0},
	{Pro102: 0},
	{Pro103: 0},
	{Pro104: 0},
	{Pro105: 0},
	{Pro106: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Text126: 0},
	{Text127: 0},
	{Text128: 0},
	{Text129: 0},
	{Text130: 0},
	{Text131: 0},
	{Text132: 0},
	{Text133: 0},
	{Text134: 0},
	{Text135: 0},
	{Text136: 0},
	{Pro107: 0},
	{Pro108: 0},
	{Pro109: 0},
	{Pro110: 0},
	{Pro111: 0},
	{Pro113: 0},
	{Pro114: 0},
	{Pro115: 0},
	{Pro116: 0},
	{Text137: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Text138: 0},
	{Text139: 0},
	{Text140: 0},
	{Text141: 0},
	{Text142: 0},
	{Text143: 0},
	{Text144: 0},
	{Text145: 0},
	{Text146: 0},
	{Text147: 0},
	{Pro117: 0},
	{Pro118: 0},
	{Pro119: 0},
	{Pro120: 0},
	{Pro121: 0},
	{Pro124: 0},
	{Pro125: 0},
	{Pro126: 0},
	{Text148: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Text149: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Text150: 0},
	{Text151: 0},
	{Text152: 0},
	{Text153: 0},
	{Text154: 0},
	{Text155: 0},
	{Text156: 0},
	{Text157: 0},
	{Text158: 0},
	{Pro127: 0},
	{Pro128: 0},
	{Pro129: 0},
	{Pro130: 0},
	{Pro131: 0},
	{Pro132: 0},
	{Pro133: 0},
	{Pro134: 0},
	{Pro135: 0},
	{ProBug01: 0},
	{ProBug02: 0},
	{ProBug03: 0},
	{Text159: 0},
	{Text160: 0},
	{Text161: 0},
	{Text162: 0},
	{Text163: 0},
	{Text164: 0},
	{Text165: 0},
	{Text166: 0},
	{Pro136: 0},
	{Pro137: 0},
	{Pro138: 0},
	{Pro139: 0},
	{Pro140: 0},
	{Pro141: 0},
	{Pro142: 0},
	{Pro143: 0},
	{Text167: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Text168: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Text169: 0},
	{Text170: 0},
	{Text171: 0},
	{Text172: 0},
	{Text173: 0},
	{Text174: 0},
	{Text175: 0},
	{Text176: 0},
	{Pro144: 0},
	{Pro145: 0},
	{Pro146: 0},
	{Pro147: 0},
	{Pro148: 0},
	{Pro149: 0},
	{Pro150: 0},
	{Pro151: 0},
	{Text177: 0},
	{Text178: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Text179: 0},
	{Text180: 0},
	{Text181: 0},
	{Text182: 0},
	{Text183: 0},
	{Text184: 0},
	{Text185: 0},
	{Pro112: 0},
	{Pro122: 0},
	{Pro123: 0},
	{Pro152: 0},
	{Pro153: 0},
	{Pro154: 0},
	{Pro155: 0},
	{Pro156: 0},
	{Pro157: 0},
	{Pro158: 0},
	{Pro159: 0},
	{Text186: 0},
	{Text187: 0},
	{Text188: 0},
	{Text189: 0},
	{Text190: 0},
	{Text191: 0},
	{Text192: 0},
	{Text193: 0},
	{Sprite55: 0},
	{Pro3: 0},
	{Pro4: 0},
	{Pro5: 0},
	{Pro6: 0},
	{Pro7: 0},
	{Pro160: 0},
	{Pro161: 0},
	{Pro162: 0},
	{Pro163: 0},
	{Pro164: 0},
	{Pro165: 0},
	{Pro166: 0},
	{Pro167: 0},
	{Text194: 0},
	{Text195: 0},
	{Text196: 0},
	{Text197: 0},
	{Text198: 0},
	{Text199: 0},
	{Text200: 0},
	{Text201: 0},
	{Text202: 0},
	{Pro168: 0},
	{Pro169: 0},
	{Pro170: 0},
	{Pro171: 0},
	{Pro172: 0},
	{Pro173: 0},
	{Pro174: 0},
	{Pro175: 0},
	{Text203: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Text204: 0},
	{Text205: 0},
	{Text206: 0},
	{Text207: 0},
	{Text208: 0},
	{Text209: 0},
	{Text210: 0},
	{Text211: 0},
	{Pro176: 0},
	{Pro177: 0},
	{Pro178: 0},
	{Pro179: 0},
	{Pro180: 0},
	{Pro181: 0},
	{Pro182: 0},
	{Pro183: 0},
	{Text212: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Text213: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Text214: 0},
	{Text215: 0},
	{Text216: 0},
	{Text217: 0},
	{Text218: 0},
	{Text219: 0},
	{Text220: 0},
	{Text221: 0},
	{Pro184: 0},
	{Pro185: 0},
	{Pro186: 0},
	{Pro187: 0},
	{Pro188: 0},
	{Pro189: 0},
	{Pro190: 0},
	{Pro191: 0},
	{Text222: 0},
	{Text223: 0},
	{Text224: 0},
	{Text225: 0},
	{Text226: 0},
	{Text227: 0},
	{Text228: 0},
	{Text229: 0},
	{Pro192: 0},
	{Pro193: 0},
	{Pro194: 0},
	{Pro195: 0},
	{Pro196: 0},
	{Pro197: 0},
	{Pro198: 0},
	{Pro199: 0},
	{Sprite62: 0},
	{Text230: 0},
	{Year: 0},
	{Day: 0},
	{ArrayX: 0},
	{ArrayY: 0},
	{GridX: 0},
	{GridY: 0},
	{HasLoadedAJAX: 0},
	{Hasunlocked29: 0},
	{Hasunlocked30: 0},
	{Hasunlocked31: 0},
	{Hasunlocked32: 0},
	{Hasunlocked35: 0},
	{Hasunlocked36: 0},
	{Hasunlocked38: 0},
	{Hasunlocked39: 0},
	{Hasunlocked25: 0},
	{Hasunlocked26: 0},
	{test35: 0},
	{"35test": 0},
	{test39: 0},
	{"39test": 0},
	{test36: 0},
	{test362: 0},
	{"36test": 0},
	{"36test2": 0},
	{test38: 0},
	{"38test": 0},
	{HasUnlocked1900: 0},
	{HasUnlocked1925: 0},
	{HasUnlocked1950: 0},
	{HasUnlocked1975: 0},
	{HasUnlocked2000: 0},
	{HasUnlocked1776: 0},
	{HasUnlocked1801: 0},
	{HasUnlocked1826: 0},
	{HasUnlocked1851: 0},
	{HasUnlocked1876: 0},
	{HasUnlocked1901: 0},
	{HasUnlocked1926: 0},
	{HasUnlocked1951: 0},
	{HasUnlocked1976: 0},
	{HasUnlocked2001: 0},
	{HasUnlocked1777: 0},
	{HasUnlocked1802: 0},
	{HasUnlocked1827: 0},
	{HasUnlocked1852: 0},
	{HasUnlocked1877: 0},
	{HasUnlocked1902: 0},
	{HasUnlocked1927: 0},
	{HasUnlocked1952: 0},
	{HasUnlocked1977: 0},
	{HasUnlocked2002: 0},
	{HasUnlocked1778: 0},
	{HasUnlocked1803: 0},
	{HasUnlocked1828: 0},
	{HasUnlocked1853: 0},
	{HasUnlocked1878: 0},
	{HasUnlocked1903: 0},
	{HasUnlocked1928: 0},
	{HasUnlocked1953: 0},
	{HasUnlocked1978: 0},
	{HasUnlocked2003: 0},
	{HasUnlocked1779: 0},
	{HasUnlocked1804: 0},
	{HasUnlocked1829: 0},
	{HasUnlocked1854: 0},
	{HasUnlocked1879: 0},
	{HasUnlocked1904: 0},
	{HasUnlocked1929: 0},
	{HasUnlocked1954: 0},
	{HasUnlocked1979: 0},
	{HasUnlocked2004: 0},
	{HasUnlocked1780: 0},
	{HasUnlocked1805: 0},
	{HasUnlocked1830: 0},
	{HasUnlocked1855: 0},
	{HasUnlocked1880: 0},
	{HasUnlocked1905: 0},
	{HasUnlocked1930: 0},
	{HasUnlocked1955: 0},
	{HasUnlocked1980: 0},
	{HasUnlocked2005: 0},
	{IndustryLvl: 0},
	{HousingLvl: 0},
	{TransportLvl: 0},
	{EducationLvl: 0},
	{FarmingLvl: 0},
	{HealthLvl: 0},
	{QualityOfWorkLvl: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Season: class extends self.ISpriteInstance {},
	_1000s: class extends self.ISpriteInstance {},
	_100s: class extends self.ISpriteInstance {},
	_10s: class extends self.ISpriteInstance {},
	_1s: class extends self.ISpriteInstance {},
	_1000s2: class extends self.ISpriteInstance {},
	_1000s3: class extends self.ISpriteInstance {},
	_1000s4: class extends self.ISpriteInstance {},
	D100s: class extends self.ISpriteInstance {},
	D10s: class extends self.ISpriteInstance {},
	D1s: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Text9: class extends self.ITextInstance {},
	Text10: class extends self.ITextInstance {},
	Text11: class extends self.ITextInstance {},
	Text12: class extends self.ITextInstance {},
	Text13: class extends self.ITextInstance {},
	Text14: class extends self.ITextInstance {},
	Pro03: class extends self.ISpriteInstance {},
	Pro02: class extends self.ISpriteInstance {},
	Pro04: class extends self.ISpriteInstance {},
	Pro05: class extends self.ISpriteInstance {},
	Pro06: class extends self.ISpriteInstance {},
	Pro01: class extends self.ISpriteInstance {},
	Pro00: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Text15: class extends self.ITextInstance {},
	Text16: class extends self.ITextInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Text17: class extends self.ITextInstance {},
	Text18: class extends self.ITextInstance {},
	Text19: class extends self.ITextInstance {},
	Text20: class extends self.ITextInstance {},
	Text21: class extends self.ITextInstance {},
	Text22: class extends self.ITextInstance {},
	Text23: class extends self.ITextInstance {},
	Pro07: class extends self.ISpriteInstance {},
	Pro08: class extends self.ISpriteInstance {},
	Pro10: class extends self.ISpriteInstance {},
	Pro12: class extends self.ISpriteInstance {},
	Pro14: class extends self.ISpriteInstance {},
	Pro13: class extends self.ISpriteInstance {},
	Pro11: class extends self.ISpriteInstance {},
	Pro09: class extends self.ISpriteInstance {},
	Text24: class extends self.ITextInstance {},
	Text25: class extends self.ITextInstance {},
	Text26: class extends self.ITextInstance {},
	Text27: class extends self.ITextInstance {},
	Text28: class extends self.ITextInstance {},
	Text29: class extends self.ITextInstance {},
	Text30: class extends self.ITextInstance {},
	Pro15: class extends self.ISpriteInstance {},
	Pro16: class extends self.ISpriteInstance {},
	Pro18: class extends self.ISpriteInstance {},
	Pro20: class extends self.ISpriteInstance {},
	Pro22: class extends self.ISpriteInstance {},
	Pro17: class extends self.ISpriteInstance {},
	Pro19: class extends self.ISpriteInstance {},
	Pro21: class extends self.ISpriteInstance {},
	Text31: class extends self.ITextInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	ProgressArray: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Text32: class extends self.ITextInstance {},
	Text33: class extends self.ITextInstance {},
	Text34: class extends self.ITextInstance {},
	Text35: class extends self.ITextInstance {},
	Text36: class extends self.ITextInstance {},
	Text37: class extends self.ITextInstance {},
	Text38: class extends self.ITextInstance {},
	Text39: class extends self.ITextInstance {},
	Text40: class extends self.ITextInstance {},
	Text41: class extends self.ITextInstance {},
	Text42: class extends self.ITextInstance {},
	Text43: class extends self.ITextInstance {},
	Text44: class extends self.ITextInstance {},
	Text45: class extends self.ITextInstance {},
	Pro23: class extends self.ISpriteInstance {},
	Pro24: class extends self.ISpriteInstance {},
	Pro25: class extends self.ISpriteInstance {},
	Pro26: class extends self.ISpriteInstance {},
	Pro27: class extends self.ISpriteInstance {},
	Pro28: class extends self.ISpriteInstance {},
	Pro29: class extends self.ISpriteInstance {},
	Pro30: class extends self.ISpriteInstance {},
	Pro31: class extends self.ISpriteInstance {},
	Pro32: class extends self.ISpriteInstance {},
	Pro33: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Text46: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	Text47: class extends self.ITextInstance {},
	Text48: class extends self.ITextInstance {},
	Text49: class extends self.ITextInstance {},
	Text50: class extends self.ITextInstance {},
	Text51: class extends self.ITextInstance {},
	Text52: class extends self.ITextInstance {},
	Pro34: class extends self.ISpriteInstance {},
	Pro35: class extends self.ISpriteInstance {},
	Pro36: class extends self.ISpriteInstance {},
	Pro37: class extends self.ISpriteInstance {},
	Pro38: class extends self.ISpriteInstance {},
	Pro39: class extends self.ISpriteInstance {},
	Text53: class extends self.ITextInstance {},
	Pro40: class extends self.ISpriteInstance {},
	Pro41: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Pro42: class extends self.ISpriteInstance {},
	Text54: class extends self.ITextInstance {},
	Text55: class extends self.ITextInstance {},
	Text56: class extends self.ITextInstance {},
	Text57: class extends self.ITextInstance {},
	Text58: class extends self.ITextInstance {},
	Text59: class extends self.ITextInstance {},
	Text60: class extends self.ITextInstance {},
	Text61: class extends self.ITextInstance {},
	Text62: class extends self.ITextInstance {},
	Text63: class extends self.ITextInstance {},
	Pro43: class extends self.ISpriteInstance {},
	Pro44: class extends self.ISpriteInstance {},
	Pro45: class extends self.ISpriteInstance {},
	Pro46: class extends self.ISpriteInstance {},
	Pro47: class extends self.ISpriteInstance {},
	Pro48: class extends self.ISpriteInstance {},
	Pro49: class extends self.ISpriteInstance {},
	Text64: class extends self.ITextInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Text65: class extends self.ITextInstance {},
	Pro50: class extends self.ISpriteInstance {},
	Text66: class extends self.ITextInstance {},
	Text67: class extends self.ITextInstance {},
	Text68: class extends self.ITextInstance {},
	Text69: class extends self.ITextInstance {},
	Text70: class extends self.ITextInstance {},
	Text71: class extends self.ITextInstance {},
	Text72: class extends self.ITextInstance {},
	Pro51: class extends self.ISpriteInstance {},
	Pro52: class extends self.ISpriteInstance {},
	Pro53: class extends self.ISpriteInstance {},
	Pro54: class extends self.ISpriteInstance {},
	Pro55: class extends self.ISpriteInstance {},
	Pro56: class extends self.ISpriteInstance {},
	Pro57: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Text73: class extends self.ITextInstance {},
	Text74: class extends self.ITextInstance {},
	Text75: class extends self.ITextInstance {},
	Text76: class extends self.ITextInstance {},
	Text77: class extends self.ITextInstance {},
	Text78: class extends self.ITextInstance {},
	Text79: class extends self.ITextInstance {},
	Text80: class extends self.ITextInstance {},
	Text81: class extends self.ITextInstance {},
	Text82: class extends self.ITextInstance {},
	Text83: class extends self.ITextInstance {},
	Pro58: class extends self.ISpriteInstance {},
	Pro59: class extends self.ISpriteInstance {},
	Pro60: class extends self.ISpriteInstance {},
	Pro61: class extends self.ISpriteInstance {},
	Pro62: class extends self.ISpriteInstance {},
	Pro63: class extends self.ISpriteInstance {},
	Pro64: class extends self.ISpriteInstance {},
	Pro65: class extends self.ISpriteInstance {},
	Pro66: class extends self.ISpriteInstance {},
	Pro67: class extends self.ISpriteInstance {},
	Text84: class extends self.ITextInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Text85: class extends self.ITextInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Text86: class extends self.ITextInstance {},
	Text87: class extends self.ITextInstance {},
	Text88: class extends self.ITextInstance {},
	Text89: class extends self.ITextInstance {},
	Text90: class extends self.ITextInstance {},
	Text91: class extends self.ITextInstance {},
	Text92: class extends self.ITextInstance {},
	Text93: class extends self.ITextInstance {},
	Pro68: class extends self.ISpriteInstance {},
	Pro69: class extends self.ISpriteInstance {},
	Pro70: class extends self.ISpriteInstance {},
	Pro71: class extends self.ISpriteInstance {},
	Pro72: class extends self.ISpriteInstance {},
	Pro73: class extends self.ISpriteInstance {},
	Pro74: class extends self.ISpriteInstance {},
	Pro75: class extends self.ISpriteInstance {},
	Text94: class extends self.ITextInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Text95: class extends self.ITextInstance {},
	Pro76: class extends self.ISpriteInstance {},
	Text96: class extends self.ITextInstance {},
	Text97: class extends self.ITextInstance {},
	Text98: class extends self.ITextInstance {},
	Text99: class extends self.ITextInstance {},
	Text100: class extends self.ITextInstance {},
	Text101: class extends self.ITextInstance {},
	Text102: class extends self.ITextInstance {},
	Text103: class extends self.ITextInstance {},
	Text104: class extends self.ITextInstance {},
	Text105: class extends self.ITextInstance {},
	Text106: class extends self.ITextInstance {},
	Pro77: class extends self.ISpriteInstance {},
	Pro78: class extends self.ISpriteInstance {},
	Pro79: class extends self.ISpriteInstance {},
	Pro80: class extends self.ISpriteInstance {},
	Pro81: class extends self.ISpriteInstance {},
	Pro82: class extends self.ISpriteInstance {},
	Pro83: class extends self.ISpriteInstance {},
	Pro84: class extends self.ISpriteInstance {},
	Pro85: class extends self.ISpriteInstance {},
	Pro86: class extends self.ISpriteInstance {},
	Pro87: class extends self.ISpriteInstance {},
	Text107: class extends self.ITextInstance {},
	Text108: class extends self.ITextInstance {},
	Text109: class extends self.ITextInstance {},
	Text110: class extends self.ITextInstance {},
	Text111: class extends self.ITextInstance {},
	Text112: class extends self.ITextInstance {},
	Text113: class extends self.ITextInstance {},
	Text114: class extends self.ITextInstance {},
	Pro88: class extends self.ISpriteInstance {},
	Pro89: class extends self.ISpriteInstance {},
	Pro90: class extends self.ISpriteInstance {},
	Pro91: class extends self.ISpriteInstance {},
	Pro92: class extends self.ISpriteInstance {},
	Pro93: class extends self.ISpriteInstance {},
	Pro94: class extends self.ISpriteInstance {},
	Pro95: class extends self.ISpriteInstance {},
	Text115: class extends self.ITextInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Text116: class extends self.ITextInstance {},
	Text117: class extends self.ITextInstance {},
	Text118: class extends self.ITextInstance {},
	Text119: class extends self.ITextInstance {},
	Text120: class extends self.ITextInstance {},
	Text121: class extends self.ITextInstance {},
	Text122: class extends self.ITextInstance {},
	Text123: class extends self.ITextInstance {},
	Text124: class extends self.ITextInstance {},
	Text125: class extends self.ITextInstance {},
	Pro96: class extends self.ISpriteInstance {},
	Pro97: class extends self.ISpriteInstance {},
	Pro98: class extends self.ISpriteInstance {},
	Pro99: class extends self.ISpriteInstance {},
	Pro100: class extends self.ISpriteInstance {},
	Pro101: class extends self.ISpriteInstance {},
	Pro102: class extends self.ISpriteInstance {},
	Pro103: class extends self.ISpriteInstance {},
	Pro104: class extends self.ISpriteInstance {},
	Pro105: class extends self.ISpriteInstance {},
	Pro106: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Text126: class extends self.ITextInstance {},
	Text127: class extends self.ITextInstance {},
	Text128: class extends self.ITextInstance {},
	Text129: class extends self.ITextInstance {},
	Text130: class extends self.ITextInstance {},
	Text131: class extends self.ITextInstance {},
	Text132: class extends self.ITextInstance {},
	Text133: class extends self.ITextInstance {},
	Text134: class extends self.ITextInstance {},
	Text135: class extends self.ITextInstance {},
	Text136: class extends self.ITextInstance {},
	Pro107: class extends self.ISpriteInstance {},
	Pro108: class extends self.ISpriteInstance {},
	Pro109: class extends self.ISpriteInstance {},
	Pro110: class extends self.ISpriteInstance {},
	Pro111: class extends self.ISpriteInstance {},
	Pro113: class extends self.ISpriteInstance {},
	Pro114: class extends self.ISpriteInstance {},
	Pro115: class extends self.ISpriteInstance {},
	Pro116: class extends self.ISpriteInstance {},
	Text137: class extends self.ITextInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Text138: class extends self.ITextInstance {},
	Text139: class extends self.ITextInstance {},
	Text140: class extends self.ITextInstance {},
	Text141: class extends self.ITextInstance {},
	Text142: class extends self.ITextInstance {},
	Text143: class extends self.ITextInstance {},
	Text144: class extends self.ITextInstance {},
	Text145: class extends self.ITextInstance {},
	Text146: class extends self.ITextInstance {},
	Text147: class extends self.ITextInstance {},
	Pro117: class extends self.ISpriteInstance {},
	Pro118: class extends self.ISpriteInstance {},
	Pro119: class extends self.ISpriteInstance {},
	Pro120: class extends self.ISpriteInstance {},
	Pro121: class extends self.ISpriteInstance {},
	Pro124: class extends self.ISpriteInstance {},
	Pro125: class extends self.ISpriteInstance {},
	Pro126: class extends self.ISpriteInstance {},
	Text148: class extends self.ITextInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Text149: class extends self.ITextInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Text150: class extends self.ITextInstance {},
	Text151: class extends self.ITextInstance {},
	Text152: class extends self.ITextInstance {},
	Text153: class extends self.ITextInstance {},
	Text154: class extends self.ITextInstance {},
	Text155: class extends self.ITextInstance {},
	Text156: class extends self.ITextInstance {},
	Text157: class extends self.ITextInstance {},
	Text158: class extends self.ITextInstance {},
	Pro127: class extends self.ISpriteInstance {},
	Pro128: class extends self.ISpriteInstance {},
	Pro129: class extends self.ISpriteInstance {},
	Pro130: class extends self.ISpriteInstance {},
	Pro131: class extends self.ISpriteInstance {},
	Pro132: class extends self.ISpriteInstance {},
	Pro133: class extends self.ISpriteInstance {},
	Pro134: class extends self.ISpriteInstance {},
	Pro135: class extends self.ISpriteInstance {},
	ProBug01: class extends self.ISpriteInstance {},
	ProBug02: class extends self.ISpriteInstance {},
	ProBug03: class extends self.ISpriteInstance {},
	Text159: class extends self.ITextInstance {},
	Text160: class extends self.ITextInstance {},
	Text161: class extends self.ITextInstance {},
	Text162: class extends self.ITextInstance {},
	Text163: class extends self.ITextInstance {},
	Text164: class extends self.ITextInstance {},
	Text165: class extends self.ITextInstance {},
	Text166: class extends self.ITextInstance {},
	Pro136: class extends self.ISpriteInstance {},
	Pro137: class extends self.ISpriteInstance {},
	Pro138: class extends self.ISpriteInstance {},
	Pro139: class extends self.ISpriteInstance {},
	Pro140: class extends self.ISpriteInstance {},
	Pro141: class extends self.ISpriteInstance {},
	Pro142: class extends self.ISpriteInstance {},
	Pro143: class extends self.ISpriteInstance {},
	Text167: class extends self.ITextInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Text168: class extends self.ITextInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Text169: class extends self.ITextInstance {},
	Text170: class extends self.ITextInstance {},
	Text171: class extends self.ITextInstance {},
	Text172: class extends self.ITextInstance {},
	Text173: class extends self.ITextInstance {},
	Text174: class extends self.ITextInstance {},
	Text175: class extends self.ITextInstance {},
	Text176: class extends self.ITextInstance {},
	Pro144: class extends self.ISpriteInstance {},
	Pro145: class extends self.ISpriteInstance {},
	Pro146: class extends self.ISpriteInstance {},
	Pro147: class extends self.ISpriteInstance {},
	Pro148: class extends self.ISpriteInstance {},
	Pro149: class extends self.ISpriteInstance {},
	Pro150: class extends self.ISpriteInstance {},
	Pro151: class extends self.ISpriteInstance {},
	Text177: class extends self.ITextInstance {},
	Text178: class extends self.ITextInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Text179: class extends self.ITextInstance {},
	Text180: class extends self.ITextInstance {},
	Text181: class extends self.ITextInstance {},
	Text182: class extends self.ITextInstance {},
	Text183: class extends self.ITextInstance {},
	Text184: class extends self.ITextInstance {},
	Text185: class extends self.ITextInstance {},
	Pro112: class extends self.ISpriteInstance {},
	Pro122: class extends self.ISpriteInstance {},
	Pro123: class extends self.ISpriteInstance {},
	Pro152: class extends self.ISpriteInstance {},
	Pro153: class extends self.ISpriteInstance {},
	Pro154: class extends self.ISpriteInstance {},
	Pro155: class extends self.ISpriteInstance {},
	Pro156: class extends self.ISpriteInstance {},
	Pro157: class extends self.ISpriteInstance {},
	Pro158: class extends self.ISpriteInstance {},
	Pro159: class extends self.ISpriteInstance {},
	Text186: class extends self.ITextInstance {},
	Text187: class extends self.ITextInstance {},
	Text188: class extends self.ITextInstance {},
	Text189: class extends self.ITextInstance {},
	Text190: class extends self.ITextInstance {},
	Text191: class extends self.ITextInstance {},
	Text192: class extends self.ITextInstance {},
	Text193: class extends self.ITextInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Pro3: class extends self.ISpriteInstance {},
	Pro4: class extends self.ISpriteInstance {},
	Pro5: class extends self.ISpriteInstance {},
	Pro6: class extends self.ISpriteInstance {},
	Pro7: class extends self.ISpriteInstance {},
	Pro160: class extends self.ISpriteInstance {},
	Pro161: class extends self.ISpriteInstance {},
	Pro162: class extends self.ISpriteInstance {},
	Pro163: class extends self.ISpriteInstance {},
	Pro164: class extends self.ISpriteInstance {},
	Pro165: class extends self.ISpriteInstance {},
	Pro166: class extends self.ISpriteInstance {},
	Pro167: class extends self.ISpriteInstance {},
	Text194: class extends self.ITextInstance {},
	Text195: class extends self.ITextInstance {},
	Text196: class extends self.ITextInstance {},
	Text197: class extends self.ITextInstance {},
	Text198: class extends self.ITextInstance {},
	Text199: class extends self.ITextInstance {},
	Text200: class extends self.ITextInstance {},
	Text201: class extends self.ITextInstance {},
	Text202: class extends self.ITextInstance {},
	Pro168: class extends self.ISpriteInstance {},
	Pro169: class extends self.ISpriteInstance {},
	Pro170: class extends self.ISpriteInstance {},
	Pro171: class extends self.ISpriteInstance {},
	Pro172: class extends self.ISpriteInstance {},
	Pro173: class extends self.ISpriteInstance {},
	Pro174: class extends self.ISpriteInstance {},
	Pro175: class extends self.ISpriteInstance {},
	Text203: class extends self.ITextInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Text204: class extends self.ITextInstance {},
	Text205: class extends self.ITextInstance {},
	Text206: class extends self.ITextInstance {},
	Text207: class extends self.ITextInstance {},
	Text208: class extends self.ITextInstance {},
	Text209: class extends self.ITextInstance {},
	Text210: class extends self.ITextInstance {},
	Text211: class extends self.ITextInstance {},
	Pro176: class extends self.ISpriteInstance {},
	Pro177: class extends self.ISpriteInstance {},
	Pro178: class extends self.ISpriteInstance {},
	Pro179: class extends self.ISpriteInstance {},
	Pro180: class extends self.ISpriteInstance {},
	Pro181: class extends self.ISpriteInstance {},
	Pro182: class extends self.ISpriteInstance {},
	Pro183: class extends self.ISpriteInstance {},
	Text212: class extends self.ITextInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Text213: class extends self.ITextInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Text214: class extends self.ITextInstance {},
	Text215: class extends self.ITextInstance {},
	Text216: class extends self.ITextInstance {},
	Text217: class extends self.ITextInstance {},
	Text218: class extends self.ITextInstance {},
	Text219: class extends self.ITextInstance {},
	Text220: class extends self.ITextInstance {},
	Text221: class extends self.ITextInstance {},
	Pro184: class extends self.ISpriteInstance {},
	Pro185: class extends self.ISpriteInstance {},
	Pro186: class extends self.ISpriteInstance {},
	Pro187: class extends self.ISpriteInstance {},
	Pro188: class extends self.ISpriteInstance {},
	Pro189: class extends self.ISpriteInstance {},
	Pro190: class extends self.ISpriteInstance {},
	Pro191: class extends self.ISpriteInstance {},
	Text222: class extends self.ITextInstance {},
	Text223: class extends self.ITextInstance {},
	Text224: class extends self.ITextInstance {},
	Text225: class extends self.ITextInstance {},
	Text226: class extends self.ITextInstance {},
	Text227: class extends self.ITextInstance {},
	Text228: class extends self.ITextInstance {},
	Text229: class extends self.ITextInstance {},
	Pro192: class extends self.ISpriteInstance {},
	Pro193: class extends self.ISpriteInstance {},
	Pro194: class extends self.ISpriteInstance {},
	Pro195: class extends self.ISpriteInstance {},
	Pro196: class extends self.ISpriteInstance {},
	Pro197: class extends self.ISpriteInstance {},
	Pro198: class extends self.ISpriteInstance {},
	Pro199: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Text230: class extends self.ITextInstance {}
}