const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Plugins.Arr,
		C3.Plugins.Mouse,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Tilemap.Acts.SetTile,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Arr.Cnds.CompareXY
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Season: 0},
	{"1000s": 0},
	{"100s": 0},
	{"10s": 0},
	{"1s": 0},
	{"1000s2": 0},
	{"1000s3": 0},
	{"1000s4": 0},
	{D100s: 0},
	{D10s: 0},
	{D1s: 0},
	{Array: 0},
	{Sprite: 0},
	{Mouse: 0},
	{Sprite2: 0},
	{Tween: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{Text5: 0},
	{Text6: 0},
	{Text7: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Text8: 0},
	{Tilemap2: 0},
	{Text9: 0},
	{Text10: 0},
	{Text11: 0},
	{Text12: 0},
	{Text13: 0},
	{Text14: 0},
	{Pro03: 0},
	{Pro02: 0},
	{Pro04: 0},
	{Pro05: 0},
	{Pro06: 0},
	{Pro01: 0},
	{Pro00: 0},
	{Sprite22: 0},
	{Text15: 0},
	{Text16: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Text17: 0},
	{Text18: 0},
	{Text19: 0},
	{Text20: 0},
	{Text21: 0},
	{Text22: 0},
	{Text23: 0},
	{Pro07: 0},
	{Pro08: 0},
	{Pro10: 0},
	{Pro12: 0},
	{Pro14: 0},
	{Pro13: 0},
	{Pro11: 0},
	{Pro09: 0},
	{Text24: 0},
	{Text25: 0},
	{Text26: 0},
	{Text27: 0},
	{Text28: 0},
	{Text29: 0},
	{Text30: 0},
	{Pro15: 0},
	{Pro16: 0},
	{Pro18: 0},
	{Pro20: 0},
	{Pro22: 0},
	{Pro17: 0},
	{Pro19: 0},
	{Pro21: 0},
	{Text31: 0},
	{Sprite42: 0},
	{ProgressArray: 0},
	{AJAX: 0},
	{Text32: 0},
	{Text33: 0},
	{Text34: 0},
	{Text35: 0},
	{Text36: 0},
	{Text37: 0},
	{Text38: 0},
	{Text39: 0},
	{Text40: 0},
	{Text41: 0},
	{Text42: 0},
	{Text43: 0},
	{Text44: 0},
	{Text45: 0},
	{Pro23: 0},
	{Pro24: 0},
	{Pro25: 0},
	{Pro26: 0},
	{Pro27: 0},
	{Pro28: 0},
	{Pro29: 0},
	{Pro30: 0},
	{Pro31: 0},
	{Pro32: 0},
	{Pro33: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Text46: 0},
	{TextInput: 0},
	{TextInput2: 0},
	{Text47: 0},
	{Text48: 0},
	{Text49: 0},
	{Text50: 0},
	{Text51: 0},
	{Text52: 0},
	{Pro34: 0},
	{Pro35: 0},
	{Pro36: 0},
	{Pro37: 0},
	{Pro38: 0},
	{Pro39: 0},
	{Text53: 0},
	{Pro40: 0},
	{Pro41: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Pro42: 0},
	{Text54: 0},
	{Text55: 0},
	{Text56: 0},
	{Text57: 0},
	{Text58: 0},
	{Text59: 0},
	{Text60: 0},
	{Text61: 0},
	{Text62: 0},
	{Text63: 0},
	{Pro43: 0},
	{Pro44: 0},
	{Pro45: 0},
	{Pro46: 0},
	{Pro47: 0},
	{Pro48: 0},
	{Pro49: 0},
	{Text64: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Text65: 0},
	{Pro50: 0},
	{Year: 0},
	{Day: 0},
	{ArrayX: 0},
	{ArrayY: 0},
	{GridX: 0},
	{GridY: 0},
	{HasLoadedAJAX: 0},
	{HasUnlocked1775: 0},
	{HasUnlocked1800: 0},
	{HasUnlocked1825: 0},
	{HasUnlocked1850: 0},
	{HasUnlocked1875: 0},
	{HasUnlocked1900: 0},
	{HasUnlocked1925: 0},
	{HasUnlocked1950: 0},
	{HasUnlocked1975: 0},
	{HasUnlocked2000: 0},
	{Hasunlocked29: 0},
	{Hasunlocked30: 0},
	{Hasunlocked31: 0},
	{Hasunlocked32: 0},
	{Hasunlocked35: 0},
	{Hasunlocked36: 0},
	{Hasunlocked38: 0},
	{Hasunlocked39: 0},
	{Hasunlocked25: 0},
	{Hasunlocked26: 0},
	{test35: 0},
	{"35test": 0},
	{test39: 0},
	{"39test": 0},
	{test36: 0},
	{test362: 0},
	{"36test": 0},
	{"36test2": 0},
	{test38: 0},
	{"38test": 0},
	{HasUnlocked1776: 0},
	{HasUnlocked1801: 0},
	{HasUnlocked1826: 0},
	{HasUnlocked1851: 0},
	{HasUnlocked1876: 0},
	{HasUnlocked1901: 0},
	{HasUnlocked1926: 0},
	{HasUnlocked1951: 0},
	{HasUnlocked1976: 0},
	{HasUnlocked2001: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Season: class extends self.ISpriteInstance {},
	_1000s: class extends self.ISpriteInstance {},
	_100s: class extends self.ISpriteInstance {},
	_10s: class extends self.ISpriteInstance {},
	_1s: class extends self.ISpriteInstance {},
	_1000s2: class extends self.ISpriteInstance {},
	_1000s3: class extends self.ISpriteInstance {},
	_1000s4: class extends self.ISpriteInstance {},
	D100s: class extends self.ISpriteInstance {},
	D10s: class extends self.ISpriteInstance {},
	D1s: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Text9: class extends self.ITextInstance {},
	Text10: class extends self.ITextInstance {},
	Text11: class extends self.ITextInstance {},
	Text12: class extends self.ITextInstance {},
	Text13: class extends self.ITextInstance {},
	Text14: class extends self.ITextInstance {},
	Pro03: class extends self.ISpriteInstance {},
	Pro02: class extends self.ISpriteInstance {},
	Pro04: class extends self.ISpriteInstance {},
	Pro05: class extends self.ISpriteInstance {},
	Pro06: class extends self.ISpriteInstance {},
	Pro01: class extends self.ISpriteInstance {},
	Pro00: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Text15: class extends self.ITextInstance {},
	Text16: class extends self.ITextInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Text17: class extends self.ITextInstance {},
	Text18: class extends self.ITextInstance {},
	Text19: class extends self.ITextInstance {},
	Text20: class extends self.ITextInstance {},
	Text21: class extends self.ITextInstance {},
	Text22: class extends self.ITextInstance {},
	Text23: class extends self.ITextInstance {},
	Pro07: class extends self.ISpriteInstance {},
	Pro08: class extends self.ISpriteInstance {},
	Pro10: class extends self.ISpriteInstance {},
	Pro12: class extends self.ISpriteInstance {},
	Pro14: class extends self.ISpriteInstance {},
	Pro13: class extends self.ISpriteInstance {},
	Pro11: class extends self.ISpriteInstance {},
	Pro09: class extends self.ISpriteInstance {},
	Text24: class extends self.ITextInstance {},
	Text25: class extends self.ITextInstance {},
	Text26: class extends self.ITextInstance {},
	Text27: class extends self.ITextInstance {},
	Text28: class extends self.ITextInstance {},
	Text29: class extends self.ITextInstance {},
	Text30: class extends self.ITextInstance {},
	Pro15: class extends self.ISpriteInstance {},
	Pro16: class extends self.ISpriteInstance {},
	Pro18: class extends self.ISpriteInstance {},
	Pro20: class extends self.ISpriteInstance {},
	Pro22: class extends self.ISpriteInstance {},
	Pro17: class extends self.ISpriteInstance {},
	Pro19: class extends self.ISpriteInstance {},
	Pro21: class extends self.ISpriteInstance {},
	Text31: class extends self.ITextInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	ProgressArray: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Text32: class extends self.ITextInstance {},
	Text33: class extends self.ITextInstance {},
	Text34: class extends self.ITextInstance {},
	Text35: class extends self.ITextInstance {},
	Text36: class extends self.ITextInstance {},
	Text37: class extends self.ITextInstance {},
	Text38: class extends self.ITextInstance {},
	Text39: class extends self.ITextInstance {},
	Text40: class extends self.ITextInstance {},
	Text41: class extends self.ITextInstance {},
	Text42: class extends self.ITextInstance {},
	Text43: class extends self.ITextInstance {},
	Text44: class extends self.ITextInstance {},
	Text45: class extends self.ITextInstance {},
	Pro23: class extends self.ISpriteInstance {},
	Pro24: class extends self.ISpriteInstance {},
	Pro25: class extends self.ISpriteInstance {},
	Pro26: class extends self.ISpriteInstance {},
	Pro27: class extends self.ISpriteInstance {},
	Pro28: class extends self.ISpriteInstance {},
	Pro29: class extends self.ISpriteInstance {},
	Pro30: class extends self.ISpriteInstance {},
	Pro31: class extends self.ISpriteInstance {},
	Pro32: class extends self.ISpriteInstance {},
	Pro33: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Text46: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	Text47: class extends self.ITextInstance {},
	Text48: class extends self.ITextInstance {},
	Text49: class extends self.ITextInstance {},
	Text50: class extends self.ITextInstance {},
	Text51: class extends self.ITextInstance {},
	Text52: class extends self.ITextInstance {},
	Pro34: class extends self.ISpriteInstance {},
	Pro35: class extends self.ISpriteInstance {},
	Pro36: class extends self.ISpriteInstance {},
	Pro37: class extends self.ISpriteInstance {},
	Pro38: class extends self.ISpriteInstance {},
	Pro39: class extends self.ISpriteInstance {},
	Text53: class extends self.ITextInstance {},
	Pro40: class extends self.ISpriteInstance {},
	Pro41: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Pro42: class extends self.ISpriteInstance {},
	Text54: class extends self.ITextInstance {},
	Text55: class extends self.ITextInstance {},
	Text56: class extends self.ITextInstance {},
	Text57: class extends self.ITextInstance {},
	Text58: class extends self.ITextInstance {},
	Text59: class extends self.ITextInstance {},
	Text60: class extends self.ITextInstance {},
	Text61: class extends self.ITextInstance {},
	Text62: class extends self.ITextInstance {},
	Text63: class extends self.ITextInstance {},
	Pro43: class extends self.ISpriteInstance {},
	Pro44: class extends self.ISpriteInstance {},
	Pro45: class extends self.ISpriteInstance {},
	Pro46: class extends self.ISpriteInstance {},
	Pro47: class extends self.ISpriteInstance {},
	Pro48: class extends self.ISpriteInstance {},
	Pro49: class extends self.ISpriteInstance {},
	Text64: class extends self.ITextInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Text65: class extends self.ITextInstance {},
	Pro50: class extends self.ISpriteInstance {}
}